# We need to setup different context root for the auth server so that we can store separate
# cookies for both the API gateway as well as the OAuth2 authorization server.
server:
  port: 8899
  contextPath: /userauth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  user:
    password: password

# Datasource and JPA configuration to be used for storing the OAuth authorization details
# and token store
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
